export const menulists = [
  {
    id: 1,
    path: "/",
    link: "home",
  },
  {
    id: 2,
    // path: "/product",
    link: "product",
    children: true,
  },
  {
    id: 3,
    path: "/blog",
    link: "Blog",
  },
  {
    id: 4,
    path: "/about",
    link: "about",
  },
  // {
  //   id: 5,
  //   path: "/services",
  //   link: "Services",
  // },
  {
    id: 6,
    path: "/contact",
    link: "Contact",
  },
  {
    id: 7,
    path: "/room-chat",
    link: "Chat Video",
  },
];

export const categorylists = [
  {
    id: 1,
    image: "../images/category/c2.png",
    title: "electronics",
  },
  {
    id: 2,
    image: "../images/category/book.png",
    title: "books",
  },
  {
    id: 3,
    image: "../images/category/art.jpg",
    title: "arts",
  },
  {
    id: 4,
    image: "../images/category/watch.jpg",
    title: "watches",
  },
  {
    id: 5,
    image: "../images/category/coin.jpg",
    title: "coins",
  },
  // {
  //   id: 6,
  //   image: "../images/category/toy.png",
  //   title: "toys",
  // },
  // {
  //   id: 7,
  //   image: "../images/category/c7.png",
  //   title: "clothes",
  // },
];

export const productlists = [
  {
    id: 1,
    image: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/nuron-art-demo-image-7-768x768.png",
    title: "Blown Glass Creations for Every Occasion",
    bprice: 853,
    price: 5000,
    catgeory: "Arts",
  },
  {
    id: 2,
    image: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/nuron-art-demo-image-8-390x532.png",
    title: "Capturing Nature’s Beauty",
    bprice: 452,
    price: 1420,
    catgeory: "Arts",
  },
  {
    id: 3,
    image: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/nuron-art-demo-image-1-390x532.png",
    title: "Ceramic Tea Sets with a Twist",
    bprice: 105,
    price: 100,
    catgeory: "Arts",
  },
  {
    id: 4,
    image: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-01-600x600.jpg",
    title: "Vintage Motorcycles and Scooters",
    bprice: 40000,
    price: 50000,
    catgeory: "Automotive",
  },
  {
    id: 5,
    image: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-02-600x600.jpg",
    title: "Off-Road Adventure Seekers",
    bprice: 4000,
    price: 8000,
    catgeory: "Automotive",
  },
  {
    id: 6,
    image: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-04-600x600.jpg",
    title: "Rare Exotics and Supercars",
    bprice: 40000,
    price: 80000,
    catgeory: "Automotive",
  },
  {
    id: 6,
    image: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/books_demo_product_07-600x600.jpg",
    title: "Rare Exotics and Supercars",
    bprice: 400,
    price: 800,
    catgeory: "Romantic Escapes",
  },
  {
    id: 7,
    image: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/books_demo_product_02-600x600.jpg",
    title: "Epic Fantasy Chronicles",
    bprice: 200,
    price: 800,
    catgeory: "Romantic Escapes",
  },
  {
    id: 8,
    image: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/books_demo_product_09-600x600.jpg",
    title: "Graphic Non-Fiction",
    bprice: 200,
    price: 800,
    catgeory: "Romantic Escapes",
  },
  {
    id: 9,
    image: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/coin-auction-demo-product-10-768x768.jpg",
    title: "Coin Hyundai Sonata",
    bprice: 853,
    price: 5000,
    catgeory: "Arts",
  },
  {
    id: 10,
    image: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/coin-auction-demo-product-07-768x768.jpg",
    title: "2018 Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 11,
    image: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/lab-product-05-768x768.jpg",
    title: "2018 Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://netstorm-react.theme-land.com/img/auction_4.jpg",
    title: "2018 Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://netstorm-react.theme-land.com/img/auction_5.jpg",
    title: "2018 Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://netstorm-react.theme-land.com/img/auction_6.jpg",
    title: "2018 Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://netstorm-react.theme-land.com/img/auction_7.jpg",
    title: "2018 Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://netstorm-react.theme-land.com/img/auction_8.jpg",
    title: "2018 Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-10.jpg",
    title: "2018 Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/antiques-demo-product-09-768x768.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://bidpro.webdevia.com/wp-content/uploads/2018/12/photo-1596568359553-a56de6970068-600x414.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://bidpro.webdevia.com/wp-content/uploads/2018/05/florian-klauer-mk7D-4UCfmg-unsplash-600x414.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://bidpro.webdevia.com/wp-content/uploads/2018/05/igor-karimov-59MGmlUiqwA-unsplash-600x414.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://bidpro.webdevia.com/real-estate-auction-marketplace/wp-content/uploads/sites/5/2022/03/home-9-1-450x338.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/antiques-demo-product-10-768x768.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://jew-theme.myshopify.com/cdn/shop/files/Rectangle_144.png?v=1703498789&width=1500",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://themesflat.co/html/open9/assets/images/box-item/card-item-05.jpg",
    title: "2018 Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://themesflat.co/html/open9/assets/images/box-item/card-item-06.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://themesflat.co/html/open9/assets/images/box-item/card-item-07.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://themesflat.co/html/open9/assets/images/box-item/card-item-08.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://themesflat.co/html/open9/assets/images/box-item/card-item-01.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://themesflat.co/html/open9/assets/images/box-item/card-item-02.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://themesflat.co/html/open9/assets/images/box-item/card-item-03.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://themesflat.co/html/open9/assets/images/box-item/card-item-04.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
];

export const processList = [
  {
    id: "01",
    title: "Sign Up",
    desc: "Sign up for our bidding website easily through the contact form. Simply provide a few pictures of the items you'd like to auction, and set up to start bidding and selling in no time!",
    cover: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/shape-7.png",
  },
  {
    id: "02",
    title: "Auction Goes Online",
    desc: "Sellers can open an auction, set the starting price, and choose an unlimited bidding duration. Enjoy complete control over your auction, with no time limits or restrictions on bids!",
    cover: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/auction.png",
  },
  {
    id: "03",
    title: "Closing Auction",
    desc: "After the viewing day(s) the auction is still a few days open for new bids. Sellers evaluate the highest bid after the closing of an auction.",
    cover: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/auction-2.png",
  },
  {
    id: "04",
    title: "Last Step",
    desc: "Once the item is sold to the highest bidder, it will be available for pickup on a scheduled date. Buyers will be notified with all the details to collect their winning items.",
    cover: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/auction-3.png",
  },
];

export const topSellerList = [
  {
    id: 1,
    title: "William",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-5-1.png",
    amount: "100",
  },
  {
    id: 2,
    title: "Orko",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-6.png",
    amount: "200",
  },
  {
    id: 3,
    title: "Nipa",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-3.png",
    amount: "300",
  },
  {
    id: 4,
    title: "Joseph",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-2-2.png",
    amount: "100",
  },
  {
    id: 5,
    title: "Isabella",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-10-2.png",
    amount: "100",
  },
  {
    id: 6,
    title: "Emily",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-15-1.png",
    amount: "100",
  },
  {
    id: 7,
    title: "Devmahbub",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-8-3.png",
    amount: "100",
  },
  {
    id: 8,
    title: "Ava Garcia",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-4-1.png",
    amount: "100",
  },
  {
    id: 9,
    title: "Amelia Harris",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-13.png",
    amount: "100",
  },
  {
    id: 10,
    title: "Alexander",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-8.png",
    amount: "100",
  },
];

export const trustList = [
  {
    id: 1,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor1.png",
  },
  {
    id: 2,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor3.png",
  },
  {
    id: 3,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor2.png",
  },
  {
    id: 4,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor4.png",
  },
  {
    id: 5,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor5.png",
  },
  {
    id: 6,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor6.png",
  },
  {
    id: 7,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor7.png",
  },
  {
    id: 8,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor8.png",
  },
  {
    id: 9,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor9.png",
  },
  {
    id: 10,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor1.png",
  },
  {
    id: 4,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor3.png",
  },
  {
    id: 5,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor8.png",
  },
  {
    id: 6,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor1.png",
  },
  {
    id: 7,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor9.png",
  },
];

export const topList = [
  {
    id: 1,
    catgeory: "Electronics",
    total: 7,
    img1: "https://media.wired.com/photos/65e873e6a982e7c6566b6bf7/master/w_2560%2Cc_limit/unnamed-11.jpg",
    img2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA9-GA493vltjJqaYpReKziCyx0Cd6uZ480w&s",
    img3: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-TBGPxer37Y1G7IRZA4GpMGEv-mNOjar8ig&s",
    img4: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvv0rpkHlgHA9hofMhuQbjy9ndTy2NGHyw8g&s",
  },
  {
    id: 2,
    catgeory: "Books",
    total: 10,
    img1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQG4BNIsEPZeAENjhrpzP20f-25EgdEdxqx5g&s",
    img2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHF8g3Q-XBi3XiM6YxGWRwf1Bmay4LViqA2g&s",
    img3: "https://images.pexels.com/photos/15202787/pexels-photo-15202787/free-photo-of-hand-holding-book-in-turkish.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    img4: "https://images.pexels.com/photos/904620/pexels-photo-904620.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
  },
  {
    id: 3,
    catgeory: "Arts",
    total: 8,
    img1: "https://images.pexels.com/photos/3459713/pexels-photo-3459713.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    img2: "https://images.pexels.com/photos/4576918/pexels-photo-4576918.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    img4: "https://images.pexels.com/photos/2763966/pexels-photo-2763966.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    img3: "https://images.pexels.com/photos/27063859/pexels-photo-27063859/free-photo-of-photo-of-the-map-of-italy.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 4,
    catgeory: "Coins",
    total: 4,
    img3: "https://images.pexels.com/photos/1235971/pexels-photo-1235971.jpeg?auto=compress&cs=tinysrgb&w=600",
    img2: "https://images.pexels.com/photos/15195541/pexels-photo-15195541/free-photo-of-independence-edition-coin.jpeg?auto=compress&cs=tinysrgb&w=600",
    img4: "https://images.pexels.com/photos/18084818/pexels-photo-18084818/free-photo-of-bitcoin-is-falling.jpeg?auto=compress&cs=tinysrgb&w=600",
    img1: "https://images.pexels.com/photos/4715172/pexels-photo-4715172.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
];
